name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy Changes
        run: |
          # Ensure the target directory exists
          sudo mkdir -p /var/www/html/website2

          # Set the correct permissions
          sudo chown -R $USER:$USER /var/www/html/website2

          # Copy the contents of the repository to the target directory
          sudo cp -r * /var/www/html/website2

          # Set the correct permissions for the files
          sudo chmod -R 755 /var/www/html/website2

          # Print a success message
          echo "Deployment to /var/www/html/website2 completed successfully."

